import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics textbook
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: Foundations of Physical AI',
          items: [
            'modules/module-1-foundations/chapter-1-intro/lesson-1-what-is-physical-ai',
            'modules/module-1-foundations/chapter-1-intro/lesson-2-digital-physical-gap',
            'modules/module-1-foundations/chapter-1-intro/lesson-3-humanoid-robotics-overview',
            'modules/module-1-foundations/chapter-1-intro/lesson-4-simulation-first-approach',
            'modules/module-1-foundations/chapter-1-intro/lesson-5-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 2: ROS 2 - The Robotic Nervous System',
          items: [
            'modules/module-2-ros/chapter-1-intro/lesson-1-ros2-overview',
            'modules/module-2-ros/chapter-1-intro/lesson-2-chapter-summary',
            'modules/module-2-ros/chapter-2-nodes/lesson-1-nodes-in-depth',
            'modules/module-2-ros/chapter-2-nodes/lesson-2-topics-and-messages',
            'modules/module-2-ros/chapter-2-nodes/lesson-3-services-and-actions',
            'modules/module-2-ros/chapter-2-nodes/lesson-4-chapter-summary',
            'modules/module-2-ros/chapter-3-topics/lesson-1-python-agents-integration',
            'modules/module-2-ros/chapter-3-topics/lesson-2-advanced-integration-techniques',
            'modules/module-2-ros/chapter-3-topics/lesson-3-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 3: Simulation and Physics Engines',
          items: [
            'modules/module-3-simulation/chapter-1-gazebo/lesson-1-introduction-to-gazebo',
            'modules/module-3-simulation/chapter-1-gazebo/lesson-2-advanced-simulation-techniques',
            'modules/module-3-simulation/chapter-1-gazebo/lesson-3-chapter-summary',
            'modules/module-3-simulation/chapter-2-physics/lesson-1-physics-engines',
            'modules/module-3-simulation/chapter-2-physics/lesson-2-collision-detection',
            'modules/module-3-simulation/chapter-2-physics/lesson-3-chapter-summary',
            'modules/module-3-simulation/chapter-3-sensors/lesson-1-sensor-modeling',
            'modules/module-3-simulation/chapter-3-sensors/lesson-2-data-fusion',
            'modules/module-3-simulation/chapter-3-sensors/lesson-3-chapter-summary',
            'modules/module-3-simulation/chapter-4-unity/lesson-1-unity-integration',
            'modules/module-3-simulation/chapter-4-unity/lesson-2-workflows',
            'modules/module-3-simulation/chapter-4-unity/lesson-3-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 4: AI Control and Learning',
          items: [
            'modules/module-4-ai-control/chapter-1-navigation/lesson-1-path-planning',
            'modules/module-4-ai-control/chapter-1-navigation/lesson-2-obstacle-avoidance',
            'modules/module-4-ai-control/chapter-1-navigation/lesson-3-chapter-summary',
            'modules/module-4-ai-control/chapter-2-manipulation/lesson-1-kinematics',
            'modules/module-4-ai-control/chapter-2-manipulation/lesson-2-grasping',
            'modules/module-4-ai-control/chapter-2-manipulation/lesson-3-chapter-summary',
            'modules/module-4-ai-control/chapter-3-vision/lesson-1-computer-vision',
            'modules/module-4-ai-control/chapter-3-vision/lesson-2-object-detection',
            'modules/module-4-ai-control/chapter-3-vision/lesson-3-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 5: Vision-Language-Action Models',
          items: [
            'modules/module-5-vla/chapter-1-intro/lesson-1-vla-overview',
            'modules/module-5-vla/chapter-1-intro/lesson-2-multimodal-learning',
            'modules/module-5-vla/chapter-1-intro/lesson-3-chapter-summary',
            'modules/module-5-vla/chapter-2-language/lesson-1-language-understanding',
            'modules/module-5-vla/chapter-2-language/lesson-2-natural-language-processing',
            'modules/module-5-vla/chapter-2-language/lesson-3-chapter-summary',
            'modules/module-5-vla/chapter-3-action/lesson-1-action-recognition',
            'modules/module-5-vla/chapter-3-action/lesson-2-embodied-ai',
            'modules/module-5-vla/chapter-3-action/lesson-3-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 6: Humanoid Robotics',
          items: [
            'modules/module-6-humanoid/chapter-1-control/lesson-1-humanoid-design',
            'modules/module-6-humanoid/chapter-1-control/lesson-2-bipedal-locomotion',
            'modules/module-6-humanoid/chapter-1-control/lesson-3-chapter-summary',
            'modules/module-6-humanoid/chapter-2-locomotion/lesson-1-balance-control',
            'modules/module-6-humanoid/chapter-2-locomotion/lesson-2-walking-algorithms',
            'modules/module-6-humanoid/chapter-2-locomotion/lesson-3-chapter-summary',
            'modules/module-6-humanoid/chapter-3-embodiment/lesson-1-human-robot-interaction',
            'modules/module-6-humanoid/chapter-3-embodiment/lesson-2-social-robotics',
            'modules/module-6-humanoid/chapter-3-embodiment/lesson-3-chapter-summary'
          ]
        },
        {
          type: 'category',
          label: 'Module 7: Capstone Projects',
          items: [
            'modules/module-7-capstone/chapter-1-project/lesson-1-project-planning',
            'modules/module-7-capstone/chapter-1-project/lesson-2-requirements-analysis',
            'modules/module-7-capstone/chapter-1-project/lesson-3-chapter-summary',
            'modules/module-7-capstone/chapter-2-implementation/lesson-1-system-integration',
            'modules/module-7-capstone/chapter-2-implementation/lesson-2-testing',
            'modules/module-7-capstone/chapter-2-implementation/lesson-3-chapter-summary',
            'modules/module-7-capstone/chapter-3-evaluation/lesson-1-performance-evaluation',
            'modules/module-7-capstone/chapter-3-evaluation/lesson-2-results-analysis',
            'modules/module-7-capstone/chapter-3-evaluation/lesson-3-final-summary'
          ]
        }
      ]
    }
  ],
};

export default sidebars;
